name: rateskill
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  bottom_navy_bar: ^4.2.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf